# Generated by Django 5.2.5 on 2025-11-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankRequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name_ru', models.CharField(max_length=200)),
                ('bank_name_en', models.CharField(max_length=200, verbose_name='Bank name in English')),
                ('bank_name_kg', models.CharField(max_length=200, verbose_name='Bank name in Kyrgyz')),
                ('account_number', models.CharField(max_length=50)),
                ('bik', models.CharField(max_length=20)),
                ('inn', models.CharField(max_length=20)),
                ('recipient_ru', models.CharField(max_length=300)),
                ('recipient_en', models.CharField(max_length=300, verbose_name='Recipient in English')),
                ('recipient_kg', models.CharField(max_length=300, verbose_name='Recipient in Kyrgyz')),
                ('payment_purpose_ru', models.CharField(max_length=500)),
                ('payment_purpose_en', models.CharField(max_length=500, verbose_name='Payment purpose in English')),
                ('payment_purpose_kg', models.CharField(max_length=500, verbose_name='Payment purpose in Kyrgyz')),
            ],
        ),
        migrations.CreateModel(
            name='ContactForeign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=20)),
                ('telegram', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Contact for foreign students',
                'verbose_name_plural': 'Contacts for foreign students',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('working_hours', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ru', models.CharField(max_length=300)),
                ('question_en', models.CharField(max_length=300, verbose_name='Question in English')),
                ('question_kg', models.CharField(max_length=300, verbose_name='Question in Kyrgyz')),
                ('answer_ru', models.TextField(verbose_name='Answer in Russian')),
                ('answer_en', models.TextField(verbose_name='Answer in English')),
                ('answer_kg', models.TextField(verbose_name='Answer in Kyrgyz')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, verbose_name='Title in English')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Title in Kyrgyz')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='В сомах')),
                ('faculty_ru', models.CharField(max_length=200, verbose_name='Faculty in Russian')),
                ('faculty_en', models.CharField(max_length=200, verbose_name='Faculty in English')),
                ('faculty_kg', models.CharField(max_length=200, verbose_name='Faculty in Kyrgyz')),
                ('warnings_ru', models.JSONField(blank=True, null=True, verbose_name='Warnings')),
                ('warnings_en', models.JSONField(blank=True, null=True, verbose_name='Warnings')),
                ('warnings_kg', models.JSONField(blank=True, null=True, verbose_name='Warnings')),
            ],
            options={
                'verbose_name': 'цена контракта(kg)',
                'verbose_name_plural': 'цены контрактов(kg)',
            },
        ),
        migrations.CreateModel(
            name='FeeForeign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, verbose_name='Title in English')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Title in Kyrgyz')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='В долларах')),
                ('faculty_ru', models.CharField(max_length=200, verbose_name='Faculty in Russian')),
                ('faculty_en', models.CharField(max_length=200, verbose_name='Faculty in English')),
                ('faculty_kg', models.CharField(max_length=200, verbose_name='Faculty in Kyrgyz')),
                ('warnings_ru', models.JSONField(blank=True, null=True, verbose_name='Warnings')),
                ('warnings_en', models.JSONField(blank=True, null=True, verbose_name='Warnings')),
                ('warnings_kg', models.JSONField(blank=True, null=True, verbose_name='Warnings')),
            ],
            options={
                'verbose_name': 'цена контракта(иностранный)',
                'verbose_name_plural': 'цены контрактов(иностранный)',
            },
        ),
        migrations.CreateModel(
            name='requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, verbose_name='Title in English')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Title in Kyrgyz')),
                ('description_ru', models.TextField(verbose_name='Description in Russian')),
                ('description_en', models.TextField(verbose_name='Description in English')),
                ('description_kg', models.TextField(verbose_name='Description in Kyrgyz')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitiesForeign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name_ru', models.CharField(max_length=200)),
                ('bank_name_en', models.CharField(max_length=200, verbose_name='Bank name in English')),
                ('bank_name_kg', models.CharField(max_length=200, verbose_name='Bank name in Kyrgyz')),
                ('account_number', models.CharField(max_length=50)),
                ('swift_code', models.CharField(max_length=20)),
                ('recipient_ru', models.CharField(max_length=300)),
                ('recipient_en', models.CharField(max_length=300, verbose_name='Recipient in English')),
                ('recipient_kg', models.CharField(max_length=300, verbose_name='Recipient in Kyrgyz')),
                ('correspondent_bank', models.CharField(max_length=300, verbose_name='Correspondent Bank')),
                ('warnings_ru', models.JSONField(blank=True, null=True, verbose_name='Warnings')),
                ('warnings_en', models.JSONField(blank=True, null=True, verbose_name='Warnings')),
                ('warnings_kg', models.JSONField(blank=True, null=True, verbose_name='Warnings')),
            ],
            options={
                'verbose_name': 'Requisities for foreign students',
                'verbose_name_plural': 'Requisities for foreign students',
            },
        ),
    ]
