# Generated by Django 5.2.5 on 2025-11-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_life', '0009_eresourcecategory_eresource_eresourcefeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='название файла(ru)')),
                ('title_kg', models.CharField(max_length=255, verbose_name='название файла(kg)')),
                ('title_en', models.CharField(max_length=255, verbose_name='название файла(en)')),
                ('file', models.FileField(upload_to='student_life/instruction_files/', verbose_name='файл')),
            ],
            options={
                'verbose_name': 'Файл инструкции',
                'verbose_name_plural': 'Файлы инструкций',
            },
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото студенческой жизни', 'verbose_name_plural': 'Фото студенческой жизни'},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='order',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photographer',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='tags_en',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='tags_kg',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='tags_ru',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title_kg',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.AddField(
            model_name='photo',
            name='category_en',
            field=models.CharField(default='def', max_length=255, verbose_name='Категория(en)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='category_kg',
            field=models.CharField(default='def', max_length=255, verbose_name='Категория(kg)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='category_ru',
            field=models.CharField(default='def', max_length=255, verbose_name='Категория(ru)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='def', upload_to='student_life/photos/', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_en',
            field=models.CharField(max_length=255, verbose_name='Описание(en)'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_kg',
            field=models.CharField(max_length=255, verbose_name='Описание(kg)'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_ru',
            field=models.CharField(max_length=255, verbose_name='Описание(ru)'),
        ),
    ]
