# Generated by Django 5.1.2 on 2025-11-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_life', '0010_instructionfiles_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='название файла(ru)')),
                ('title_kg', models.CharField(max_length=255, verbose_name='название файла(kg)')),
                ('title_en', models.CharField(max_length=255, verbose_name='название файла(en)')),
                ('description_ru', models.CharField(max_length=255, verbose_name='Описание(ru)')),
                ('description_kg', models.CharField(max_length=255, verbose_name='Описание(kg)')),
                ('description_en', models.CharField(max_length=255, verbose_name='Описание(en)')),
                ('features_ru', models.JSONField(default=list, verbose_name='особенности(ru)')),
                ('features_kg', models.JSONField(default=list, verbose_name='особенности(kg)')),
                ('features_en', models.JSONField(default=list, verbose_name='особенности(en)')),
            ],
            options={
                'verbose_name': 'Обмен',
                'verbose_name_plural': 'Обмены',
            },
        ),
    ]
