# Generated by Django 5.2.5 on 2025-11-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название (RU)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Название (EN)')),
                ('title_kg', models.CharField(blank=True, max_length=200, verbose_name='Название (KG)')),
                ('pdf_file', models.FileField(upload_to='schedule/pdfs/', verbose_name='PDF файл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Подраздел расписания',
                'verbose_name_plural': 'Подразделы расписания',
                'ordering': ['order', 'title_ru'],
            },
        ),
    ]
