# Generated by Django 5.2.5 on 2025-11-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='linksNavbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Имя ссылки (RU)')),
                ('name_kg', models.CharField(max_length=100, verbose_name='Имя ссылки (kg)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Имя ссылки (en)')),
                ('url', models.URLField(verbose_name='URL ссылки')),
            ],
            options={
                'verbose_name': 'ссылка навигационной панели',
                'verbose_name_plural': 'ссылки навигационной панели',
            },
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='numbers/icons')),
                ('number', models.CharField(max_length=20)),
                ('description_ru', models.CharField(max_length=255, verbose_name='Описание (RU)')),
                ('description_kg', models.CharField(max_length=255, verbose_name='Описание (kg)')),
                ('description_en', models.CharField(max_length=255, verbose_name='Описание (en)')),
            ],
            options={
                'verbose_name': 'секция цифры',
                'verbose_name_plural': 'секция цифры',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='testimonials/photos')),
                ('year', models.CharField(max_length=10, verbose_name='в каком курсе учится студент')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Имя студента (RU)')),
                ('name_kg', models.CharField(max_length=100, verbose_name='Имя студента (kg)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Имя студента (en)')),
                ('testimonial_ru', models.TextField(verbose_name='Отзыв студента (RU)')),
                ('testimonial_kg', models.TextField(verbose_name='Отзыв студента (kg)')),
                ('testimonial_en', models.TextField(verbose_name='Отзыв студента (en)')),
                ('faculty_ru', models.CharField(max_length=100, verbose_name='Факультет студента (RU)')),
                ('faculty_kg', models.CharField(max_length=100, verbose_name='Факультет студента (kg)')),
                ('faculty_en', models.CharField(max_length=100, verbose_name='Факультет студента (en)')),
            ],
            options={
                'verbose_name': 'отзыв студента',
                'verbose_name_plural': 'отзывы студентов',
            },
        ),
    ]
