# Generated by Django 5.2.6 on 2025-10-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_grant_application_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='journal',
        ),
        migrations.AddField(
            model_name='publication',
            name='journal_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Журнал/Издательство (англ)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal_kg',
            field=models.CharField(blank=True, max_length=300, verbose_name='Журнал/Издательство (кыр)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal_ru',
            field=models.CharField(default='Не указан', max_length=300, verbose_name='Журнал/Издательство (рус)'),
            preserve_default=False,
        ),
    ]
