# Generated by Django 5.2.6 on 2025-10-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_remove_publication_journal_publication_journal_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='journal_kg',
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal_en',
            field=models.CharField(default='', max_length=300, verbose_name='Журнал/Издательство (англ)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal_ru',
            field=models.CharField(default='', max_length=300, verbose_name='Журнал/Издательство (рус)'),
        ),
    ]
