# Generated by Django 5.2.6 on 2025-10-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_remove_publication_journal_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='journal_kg',
            field=models.CharField(default='', max_length=300, verbose_name='Журнал/Издательство (кыр)'),
        ),
    ]
