# Generated by Django 5.2.5 on 2025-11-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_publication_journal_kg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commission',
        ),
        migrations.DeleteModel(
            name='Conference',
        ),
        migrations.RemoveField(
            model_name='grantapplication',
            name='grant',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='research_area',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='research_center',
        ),
        migrations.RemoveField(
            model_name='researchmanagementposition',
            name='parent',
        ),
        migrations.DeleteModel(
            name='ScientificCouncil',
        ),
        migrations.DeleteModel(
            name='Grant',
        ),
        migrations.DeleteModel(
            name='GrantApplication',
        ),
        migrations.DeleteModel(
            name='ResearchArea',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='ResearchCenter',
        ),
        migrations.DeleteModel(
            name='ResearchManagementPosition',
        ),
    ]
