# Generated by Django 5.2.5 on 2025-11-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0009_leadership_bio_leadership_bio_en_leadership_bio_kg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intTitle', models.CharField(max_length=200, verbose_name='Заголовок-цифра')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок(ru)')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Заголовок(kg)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Заголовок(en)')),
                ('description_ru', models.TextField(verbose_name='Описание(ru)')),
                ('description_kg', models.TextField(verbose_name='Описание(kg)')),
                ('description_en', models.TextField(verbose_name='Описание(en)')),
            ],
            options={
                'verbose_name': 'ППС в цифрах',
                'verbose_name_plural': 'ППС в цифрах',
            },
        ),
        migrations.CreateModel(
            name='DetailStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intTitle', models.CharField(max_length=200, verbose_name='Заголовок-цифра')),
                ('description_ru', models.TextField(verbose_name='Описание(ru)')),
                ('description_kg', models.TextField(verbose_name='Описание(kg)')),
                ('description_en', models.TextField(verbose_name='Описание(en)')),
            ],
            options={
                'verbose_name': 'Подробная статистика',
                'verbose_name_plural': 'Подробная статистика',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название программы(ru)')),
                ('name_kg', models.CharField(max_length=200, verbose_name='Название программы(kg)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Название программы(en)')),
                ('description_ru', models.TextField(verbose_name='Описание программы(ru)')),
                ('description_kg', models.TextField(verbose_name='Описание программы(kg)')),
                ('description_en', models.TextField(verbose_name='Описание программы(en)')),
                ('profession_ru', models.CharField(max_length=200, verbose_name='Профессия(ru)')),
                ('profession_kg', models.CharField(max_length=200, verbose_name='Профессия(kg)')),
                ('profession_en', models.CharField(max_length=200, verbose_name='Профессия(en)')),
                ('duration_ru', models.CharField(max_length=100, verbose_name='Продолжительность(ru)')),
                ('duration_kg', models.CharField(max_length=100, verbose_name='Продолжительность  (kg)')),
                ('duration_en', models.CharField(max_length=100, verbose_name='Продолжительность (en)')),
                ('review_ru', models.TextField(blank=True, verbose_name='Обзор Программы(ru)')),
                ('review_kg', models.TextField(blank=True, verbose_name='Обзор Программы(kg)')),
                ('review_en', models.TextField(blank=True, verbose_name='Обзор Программы(en)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=150, verbose_name='название ресурса(ru)')),
                ('name_en', models.CharField(max_length=150, verbose_name='название ресурса(en)')),
                ('name_kg', models.CharField(max_length=150, verbose_name='название ресурса(kg)')),
                ('description_ru', models.CharField(max_length=255, verbose_name='описание ресурса(ru)')),
                ('description_kg', models.CharField(max_length=255, verbose_name='описание ресурса(kg)')),
                ('description_en', models.CharField(max_length=255, verbose_name='описание ресурса(en)')),
                ('features_ru', models.JSONField(max_length=500, verbose_name='особенности ресурса(ru)')),
                ('features_kg', models.JSONField(max_length=500, verbose_name='особенности ресурса(kg)')),
                ('features_en', models.JSONField(max_length=500, verbose_name='особенности ресурса(en)')),
                ('links', models.JSONField(verbose_name='ссылка на ресурс')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
            },
        ),
    ]
